IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'TITAN-TOOL\edi')
CREATE LOGIN [TITAN-TOOL\edi] FROM WINDOWS
GO
CREATE USER [TITAN-TOOL\edi] FOR LOGIN [TITAN-TOOL\edi] WITH DEFAULT_SCHEMA=[TITAN-TOOL\edi]
GO
