CREATE TABLE [dbo].[PMTRFM]
(
[OBJT] [int] NOT NULL,
[DCOL] [int] NULL,
[KTBL] [int] NULL,
[TLST] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMTRFM_PK] ON [dbo].[PMTRFM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
