CREATE TABLE [dbo].[PMLSRP]
(
[OBJT] [int] NOT NULL,
[CFLT] [int] NULL,
[LCLS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFLT] [int] NULL,
[SHCT] [int] NULL,
[SUBO] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMLSRP_PK] ON [dbo].[PMLSRP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
