CREATE TABLE [dbo].[PMPDMPRCT]
(
[OBJT] [int] NOT NULL,
[LNKT] [int] NULL,
[PCDT] [int] NULL,
[PCTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PNAM] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TXTV] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPDMPRCT_PK] ON [dbo].[PMPDMPRCT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
