CREATE TABLE [dbo].[PMCDMPROP]
(
[OBJT] [int] NOT NULL,
[DISP] [int] NULL,
[MAND] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCDMPROP_PK] ON [dbo].[PMCDMPROP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
