CREATE TABLE [dbo].[PMEXAS]
(
[OBJT] [int] NOT NULL,
[AATT] [int] NULL,
[CGLB] [int] NULL,
[FMLY] [int] NULL,
[SFML] [int] NULL,
[XCPL] [int] NULL,
[XCTG] [int] NULL,
[XLIB] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMEXAS_PK] ON [dbo].[PMEXAS] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
