CREATE TABLE [dbo].[PMOOMILNK]
(
[OBJT] [int] NOT NULL,
[XTYP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMILNK_PK] ON [dbo].[PMOOMILNK] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
