CREATE TABLE [dbo].[PMPDMVREF]
(
[OBJT] [int] NOT NULL,
[CROL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPDMVREF_PK] ON [dbo].[PMPDMVREF] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
