CREATE TABLE [dbo].[PMLATT]
(
[LGID] [int] NOT NULL,
[OBJT] [int] NOT NULL,
[ISTX] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMLATT_LATT] ON [dbo].[PMLATT] ([LGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMLATT_OBJT] ON [dbo].[PMLATT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
