CREATE TABLE [dbo].[PMOOMATVL]
(
[OBJT] [int] NOT NULL,
[AVAL] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMATVL_PK] ON [dbo].[PMOOMATVL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
