CREATE TABLE [dbo].[PMOOMDCSN]
(
[OBJT] [int] NOT NULL,
[EXPA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMDCSN_PK] ON [dbo].[PMOOMDCSN] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
