CREATE TABLE [dbo].[PMPDMWPRM]
(
[OBJT] [int] NOT NULL,
[DTTP] [int] NULL,
[ISEL] [int] NULL,
[PTYP] [int] NULL,
[WPDV] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPDMWPRM_PK] ON [dbo].[PMPDMWPRM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
