CREATE TABLE [dbo].[PMPDMPKCU]
(
[OBJT] [int] NOT NULL,
[DEFN] [int] NULL,
[PUBL] [int] NULL,
[RTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPKCU_PK] ON [dbo].[PMPDMPKCU] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
