CREATE TABLE [dbo].[PMILMXMOU]
(
[OBJT] [int] NOT NULL,
[TEXP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMXMOU_PK] ON [dbo].[PMILMXMOU] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
