CREATE TABLE [dbo].[PMCMRID]
(
[RKEY] [int] NOT NULL,
[UUID] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VRSN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCMRID_PK] ON [dbo].[PMCMRID] ([RKEY]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
