CREATE TABLE [dbo].[PMOOMSTAT]
(
[OBJT] [int] NOT NULL,
[FOPT] [int] NULL,
[NMSP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMSTAT_PK] ON [dbo].[PMOOMSTAT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
