CREATE TABLE [dbo].[PMCDMLINK]
(
[OBJT] [int] NOT NULL,
[CARD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDTF] [int] NULL,
[RNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCDMLINK_PK] ON [dbo].[PMCDMLINK] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
