CREATE TABLE [dbo].[PMPDMADPR]
(
[OBJT] [int] NOT NULL,
[ABST] [int] NULL,
[DEFN] [int] NULL,
[FINL] [int] NULL,
[JVMT] [int] NULL,
[JVNM] [int] NULL,
[PCDT] [int] NULL,
[PRAG] [int] NULL,
[PTYP] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STTC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMADPR_PK] ON [dbo].[PMPDMADPR] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
