CREATE TABLE [dbo].[PMILMSCEX]
(
[OBJT] [int] NOT NULL,
[SCPT] [int] NULL,
[SLNG] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMSCEX_PK] ON [dbo].[PMILMSCEX] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
