CREATE TABLE [dbo].[PMRLTN]
(
[RLTN] [int] NOT NULL,
[LIBR] [int] NOT NULL,
[CLSS] [int] NOT NULL,
[DSID] [int] NOT NULL,
[NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FLGS] [int] NOT NULL,
[PRNT] [int] NOT NULL,
[NFND] [int] NOT NULL,
[SEQN] [int] NOT NULL,
[RTYP] [int] NULL,
[LBND] [int] NULL,
[UBND] [int] NULL,
[OPST] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMRLTN_PK] ON [dbo].[PMRLTN] ([RLTN]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
