CREATE TABLE [dbo].[PMARUL]
(
[OBJT] [int] NOT NULL,
[CGLB] [int] NULL,
[FMLY] [int] NULL,
[SFML] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMARUL_PK] ON [dbo].[PMARUL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
