CREATE TABLE [dbo].[PMOCNF]
(
[CNFG] [int] NOT NULL,
[OBJT] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOCNF_PK] ON [dbo].[PMOCNF] ([CNFG], [OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
