CREATE TABLE [dbo].[PMARTF]
(
[OBJT] [int] NOT NULL,
[ENCD] [int] NULL,
[PTPL] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMARTF_PK] ON [dbo].[PMARTF] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
