CREATE TABLE [dbo].[PMILMGDOU]
(
[OBJT] [int] NOT NULL,
[TEXP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMGDOU_PK] ON [dbo].[PMILMGDOU] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
