CREATE TABLE [dbo].[PMPRJPDGM]
(
[OBJT] [int] NOT NULL,
[ECLS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EOID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCT] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPRJPDGM_PK] ON [dbo].[PMPRJPDGM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
