CREATE TABLE [dbo].[PMILMDTFL]
(
[OBJT] [int] NOT NULL,
[CRIT] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDTFL_PK] ON [dbo].[PMILMDTFL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
