CREATE TABLE [dbo].[PMCDMINHR]
(
[OBJT] [int] NOT NULL,
[COMP] [int] NULL,
[EXCL] [int] NULL,
[INHA] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCDMINHR_PK] ON [dbo].[PMCDMINHR] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
