CREATE TABLE [dbo].[PMBPMRFLW]
(
[OBJT] [int] NOT NULL,
[CNDA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDE] [int] NULL,
[CRAC] [int] NULL,
[DLAC] [int] NULL,
[FTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RDAC] [int] NULL,
[UDEF] [int] NULL,
[UPAC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMRFLW_PK] ON [dbo].[PMBPMRFLW] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
