CREATE TABLE [dbo].[PMPDMDBPK]
(
[OBJT] [int] NOT NULL,
[GENE] [int] NULL,
[INIT] [int] NULL,
[PRIV] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMDBPK_PK] ON [dbo].[PMPDMDBPK] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
