CREATE TABLE [dbo].[PMXSMXTRN]
(
[OBJT] [int] NOT NULL,
[NMSP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[XSID] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMXSMXTRN_PK] ON [dbo].[PMXSMXTRN] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
