CREATE TABLE [dbo].[PMPDMCIDX]
(
[OBJT] [int] NOT NULL,
[ASCD] [int] NULL,
[EXPR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMCIDX_PK] ON [dbo].[PMPDMCIDX] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
