CREATE TABLE [dbo].[PMPRJPCKG]
(
[OBJT] [int] NOT NULL,
[DOCI] [int] NULL,
[FOPT] [int] NULL,
[NMSP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPRJPCKG_PK] ON [dbo].[PMPRJPCKG] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
