CREATE TABLE [dbo].[PMBPMPRVD]
(
[OBJT] [int] NOT NULL,
[EURL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLNM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMLG] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMTX] [int] NULL,
[TNPF] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TNSP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMPRVD_PK] ON [dbo].[PMBPMPRVD] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
