CREATE TABLE [dbo].[PMBPMFRMT]
(
[OBJT] [int] NOT NULL,
[DEFN] [int] NULL,
[DURL] [int] NULL,
[FMTT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMFRMT_PK] ON [dbo].[PMBPMFRMT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
