CREATE TABLE [dbo].[PMPDMPERM]
(
[OBJT] [int] NOT NULL,
[GRNT] [int] NULL,
[GRTW] [int] NULL,
[RVKC] [int] NULL,
[RVOK] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPERM_PK] ON [dbo].[PMPDMPERM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
