CREATE TABLE [dbo].[PMOOMSYNC]
(
[OBJT] [int] NOT NULL,
[TMOT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMSYNC_PK] ON [dbo].[PMOOMSYNC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
