CREATE TABLE [dbo].[PMRMAP]
(
[OBJT] [int] NOT NULL,
[CRTR] [int] NULL,
[DELT] [int] NULL,
[EXPR] [int] NULL,
[INSR] [int] NULL,
[SLCT] [int] NULL,
[UPDT] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMRMAP_PK] ON [dbo].[PMRMAP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
