CREATE TABLE [dbo].[PMILMPCKG]
(
[OBJT] [int] NOT NULL,
[FOPT] [int] NULL,
[NMSP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMPCKG_PK] ON [dbo].[PMILMPCKG] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
