CREATE TABLE [dbo].[PMILMACOL]
(
[OBJT] [int] NOT NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MLEN] [int] NULL,
[PREC] [int] NULL,
[RCOL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCCE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMACOL_PK] ON [dbo].[PMILMACOL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
