CREATE TABLE [dbo].[PMCDMASSC]
(
[OBJT] [int] NOT NULL,
[GENE] [int] NULL,
[NBRC] [float] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCDMASSC_PK] ON [dbo].[PMCDMASSC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
