CREATE TABLE [dbo].[PMGUSR]
(
[GRPE] [int] NOT NULL,
[RUSR] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMGUSR_PK] ON [dbo].[PMGUSR] ([GRPE], [RUSR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMGUSR_RUSR] ON [dbo].[PMGUSR] ([RUSR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
