CREATE TABLE [dbo].[PMRPLG]
(
[OBJT] [int] NOT NULL,
[CGLB] [int] NULL,
[FMLY] [int] NULL,
[SFML] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMRPLG_PK] ON [dbo].[PMRPLG] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
