CREATE TABLE [dbo].[PMIAOB]
(
[OBJT] [int] NOT NULL,
[ACTN] [int] NULL,
[ANLZ] [int] NULL,
[EDPD] [int] NULL,
[SOID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOLC] [int] NULL,
[STYP] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMIAOB_PK] ON [dbo].[PMIAOB] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
