CREATE TABLE [dbo].[PMBPMEVNT]
(
[OBJT] [int] NOT NULL,
[DLNT] [int] NULL,
[TXPR] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMEVNT_PK] ON [dbo].[PMBPMEVNT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
