CREATE TABLE [dbo].[PMPDMINDX]
(
[OBJT] [int] NOT NULL,
[OPTS] [int] NULL,
[OTYP] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UNIQ] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMINDX_PK] ON [dbo].[PMPDMINDX] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
