CREATE TABLE [dbo].[PMPDMPKPR]
(
[OBJT] [int] NOT NULL,
[DEFN] [int] NULL,
[PCDT] [int] NULL,
[PRAG] [int] NULL,
[PUBL] [int] NULL,
[RTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPKPR_PK] ON [dbo].[PMPDMPKPR] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
