CREATE TABLE [dbo].[PMLOCK]
(
[LCKO] [int] NOT NULL,
[OBJT] [int] NOT NULL,
[LTYP] [int] NOT NULL,
[SESN] [int] NULL,
[CMMT] [int] NULL,
[WKSN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OCUS] [int] NOT NULL,
[OCDT] [datetime] NULL,
[OMUS] [int] NULL,
[OMDT] [datetime] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMLOCK_PK] ON [dbo].[PMLOCK] ([LCKO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMLOCK_OBJT] ON [dbo].[PMLOCK] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
