CREATE TABLE [dbo].[PMBPMS]
(
[OBJT] [int] NOT NULL,
[CGLB] [int] NULL,
[FMLY] [int] NULL,
[SFML] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMS_PK] ON [dbo].[PMBPMS] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
