CREATE TABLE [dbo].[PMPDMGRPE]
(
[OBJT] [int] NOT NULL,
[GRNT] [int] NULL,
[GRTW] [int] NULL,
[PASS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RVOK] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMGRPE_PK] ON [dbo].[PMPDMGRPE] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
