CREATE TABLE [dbo].[PMOOMCLNK]
(
[OBJT] [int] NOT NULL,
[CNDA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDE] [int] NULL,
[EARG] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OARG] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TACN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMCLNK_PK] ON [dbo].[PMOOMCLNK] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
