CREATE TABLE [dbo].[PMSEQN]
(
[NAME] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALE] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMSEQN_PK] ON [dbo].[PMSEQN] ([NAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
