CREATE TABLE [dbo].[PMRQMGRPE]
(
[OBJT] [int] NOT NULL,
[EMAD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMRQMGRPE_PK] ON [dbo].[PMRQMGRPE] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
