CREATE TABLE [dbo].[PMPROR]
(
[PRID] [int] NOT NULL,
[CLSS] [int] NOT NULL,
[TRET] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TDET] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RLTN] [int] NOT NULL,
[RMSK] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPROR_PK] ON [dbo].[PMPROR] ([PRID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
