CREATE TABLE [dbo].[PMDVTL]
(
[OBJT] [int] NOT NULL,
[CGLB] [int] NULL,
[FMLY] [int] NULL,
[SFML] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMDVTL_PK] ON [dbo].[PMDVTL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
