CREATE TABLE [dbo].[PMOOMACTN]
(
[OBJT] [int] NOT NULL,
[CNDA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDE] [int] NULL,
[EARG] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OARG] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PEVT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMACTN_PK] ON [dbo].[PMOOMACTN] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
