CREATE TABLE [dbo].[PMTEXT]
(
[TXID] [int] NOT NULL,
[NUMR] [int] NOT NULL,
[TDAT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TLEN] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMTEXT_TXID] ON [dbo].[PMTEXT] ([TXID], [NUMR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
