CREATE TABLE [dbo].[PMPSLM]
(
[OBJT] [int] NOT NULL,
[FNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSFI] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHCT] [int] NULL,
[SUBO] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPSLM_PK] ON [dbo].[PMPSLM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
