CREATE TABLE [dbo].[PMLDMRLSH]
(
[OBJT] [int] NOT NULL,
[CRDA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRDB] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMNT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENE] [int] NULL,
[NAMA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAMB] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMLDMRLSH_PK] ON [dbo].[PMLDMRLSH] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
