CREATE TABLE [dbo].[PMPDMPKVA]
(
[OBJT] [int] NOT NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAND] [int] NULL,
[MLEN] [int] NULL,
[PREC] [int] NULL,
[PUBL] [int] NULL,
[VACS] [int] NULL,
[VADF] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPKVA_PK] ON [dbo].[PMPDMPKVA] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
