CREATE TABLE [dbo].[PMCHCK]
(
[OBJT] [int] NOT NULL,
[ARSZ] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AVGL] [int] NULL,
[CKCN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP] [int] NULL,
[CRUL] [int] NULL,
[CTXT] [int] NULL,
[DISP] [int] NULL,
[DRVD] [int] NULL,
[DSTV] [int] NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FRMT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FRZN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDNT] [int] NULL,
[INIT] [int] NULL,
[JVNM] [int] NULL,
[LOWR] [int] NULL,
[LVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAND] [int] NULL,
[MLEN] [int] NULL,
[MULT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NMDF] [int] NULL,
[NULV] [int] NULL,
[OPTS] [int] NULL,
[PCGN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCOD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PDTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS] [int] NULL,
[PMLN] [int] NULL,
[PPRC] [int] NULL,
[PREC] [int] NULL,
[SRUL] [int] NULL,
[STTC] [int] NULL,
[UNIT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPPR] [int] NULL,
[VALS] [int] NULL,
[VISI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLTL] [int] NULL,
[WDEF] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCHCK_PK] ON [dbo].[PMCHCK] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
