CREATE TABLE [dbo].[PMBPMENDS]
(
[OBJT] [int] NOT NULL,
[ETYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMENDS_PK] ON [dbo].[PMBPMENDS] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
