CREATE TABLE [dbo].[PMEMDL]
(
[OBJT] [int] NOT NULL,
[TOID] [int] NULL,
[ECLS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EURL] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMEMDL_PK] ON [dbo].[PMEMDL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
