CREATE TABLE [dbo].[PMRRLM]
(
[NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMRRLM_PK] ON [dbo].[PMRRLM] ([NAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
