CREATE TABLE [dbo].[PMPSEL]
(
[OBJT] [int] NOT NULL,
[CRTR] [int] NULL,
[MGID] [int] NULL,
[SBLB] [int] NULL,
[STYP] [int] NULL,
[CFLT] [int] NULL,
[LCLS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMOD] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPSEL_PK] ON [dbo].[PMPSEL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
