CREATE TABLE [dbo].[PMXSMLANG]
(
[OBJT] [int] NOT NULL,
[CGLB] [int] NULL,
[FMLY] [int] NULL,
[SFML] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMXSMLANG_PK] ON [dbo].[PMXSMLANG] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
