CREATE TABLE [dbo].[PMILMFFOU]
(
[OBJT] [int] NOT NULL,
[TEXP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMFFOU_PK] ON [dbo].[PMILMFFOU] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
