CREATE TABLE [dbo].[PMSMAP]
(
[OBJT] [int] NOT NULL,
[ALIA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMSMAP_PK] ON [dbo].[PMSMAP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
