CREATE TABLE [dbo].[PMPDMNMSP]
(
[OBJT] [int] NOT NULL,
[NURI] [int] NULL,
[PRFX] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPDMNMSP_PK] ON [dbo].[PMPDMNMSP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
