CREATE TABLE [dbo].[PMPERM]
(
[POID] [int] NOT NULL,
[RUSR] [int] NOT NULL,
[OPRM] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPERM_PK] ON [dbo].[PMPERM] ([POID], [RUSR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMPERM_RUSR] ON [dbo].[PMPERM] ([RUSR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
