CREATE TABLE [dbo].[PMEOBJ]
(
[OBJT] [int] NOT NULL,
[TOID] [int] NULL,
[ECLS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EOID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENE] [int] NULL,
[GTYP] [int] NULL,
[LOCT] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMEOBJ_PK] ON [dbo].[PMEOBJ] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
