CREATE TABLE [dbo].[PMILMDTCL]
(
[OBJT] [int] NOT NULL,
[CRIT] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDTCL_PK] ON [dbo].[PMILMDTCL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
