CREATE TABLE [dbo].[PMILMTPRC]
(
[OBJT] [int] NOT NULL,
[DTSC] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOPT] [int] NULL,
[LOGN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NMSP] [int] NULL,
[PSWD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMTPRC_PK] ON [dbo].[PMILMTPRC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
