CREATE TABLE [dbo].[PMSPCL]
(
[CLSS] [int] NOT NULL,
[SUPR] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMSPCL_PK] ON [dbo].[PMSPCL] ([CLSS], [SUPR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
