CREATE TABLE [dbo].[PMBPMMSPT]
(
[OBJT] [int] NOT NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETYP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMMSPT_PK] ON [dbo].[PMBPMMSPT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
