CREATE TABLE [dbo].[PMXSMANNT]
(
[OBJT] [int] NOT NULL,
[XSID] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMXSMANNT_PK] ON [dbo].[PMXSMANNT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
