CREATE TABLE [dbo].[PMILMDTQE]
(
[OBJT] [int] NOT NULL,
[SQRY] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDTQE_PK] ON [dbo].[PMILMDTQE] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
