CREATE TABLE [dbo].[PMENUM]
(
[CLSS] [int] NULL,
[ENID] [int] NULL,
[VALU] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMENUM_CLSS] ON [dbo].[PMENUM] ([CLSS], [ENID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
