CREATE TABLE [dbo].[PMPDMWSRV]
(
[OBJT] [int] NOT NULL,
[CNUS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LPAT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RAUT] [int] NULL,
[SCNC] [int] NULL,
[WTYP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPDMWSRV_PK] ON [dbo].[PMPDMWSRV] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
