CREATE TABLE [dbo].[PMBPMOPER]
(
[OBJT] [int] NOT NULL,
[INPN] [int] NULL,
[OPTP] [int] NULL,
[OUTN] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMOPER_PK] ON [dbo].[PMBPMOPER] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
