CREATE TABLE [dbo].[PMPRJCELL]
(
[OBJT] [int] NOT NULL,
[CMPL] [int] NULL,
[HPFL] [int] NULL,
[INTV] [int] NULL,
[PREV] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPRJCELL_PK] ON [dbo].[PMPRJCELL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
