CREATE TABLE [dbo].[PMILMPRMT]
(
[OBJT] [int] NOT NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MLEN] [int] NULL,
[PREC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMPRMT_PK] ON [dbo].[PMILMPRMT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
