CREATE TABLE [dbo].[PMILMDSJN]
(
[OBJT] [int] NOT NULL,
[JEXP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDSJN_PK] ON [dbo].[PMILMDSJN] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
