CREATE TABLE [dbo].[PMXNSP]
(
[OBJT] [int] NOT NULL,
[NURI] [int] NULL,
[PRFX] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMXNSP_PK] ON [dbo].[PMXNSP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
