CREATE TABLE [dbo].[PMILMDBOU]
(
[OBJT] [int] NOT NULL,
[PTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEXP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDBOU_PK] ON [dbo].[PMILMDBOU] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
