CREATE TABLE [dbo].[PMILMARTC]
(
[OBJT] [int] NOT NULL,
[CWHR] [int] NULL,
[RTBL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMARTC_PK] ON [dbo].[PMILMARTC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
