CREATE TABLE [dbo].[PMCHGS]
(
[CHGS] [int] NOT NULL,
[RUSR] [int] NOT NULL,
[LCTN] [int] NOT NULL,
[BRNC] [int] NOT NULL,
[POID] [int] NULL,
[OUSR] [int] NOT NULL,
[ODAT] [datetime] NOT NULL,
[NWAY] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCHGS_PK] ON [dbo].[PMCHGS] ([CHGS]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
