CREATE TABLE [dbo].[PMLBIN]
(
[LBIN] [int] NOT NULL,
[NUMR] [int] NOT NULL,
[BDAT] [image] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMLBIN_LBIN] ON [dbo].[PMLBIN] ([LBIN], [NUMR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
