CREATE TABLE [dbo].[PMILMTPRM]
(
[OBJT] [int] NOT NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTYP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMTPRM_PK] ON [dbo].[PMILMTPRM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
