CREATE TABLE [dbo].[PMILMDSCL]
(
[OBJT] [int] NOT NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCL] [int] NULL,
[MAND] [int] NULL,
[MLEN] [int] NULL,
[PREC] [int] NULL,
[SEXP] [int] NULL,
[TEXP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDSCL_PK] ON [dbo].[PMILMDSCL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
