CREATE TABLE [dbo].[PMBPMDATA]
(
[OBJT] [int] NOT NULL,
[DTYP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMDATA_PK] ON [dbo].[PMBPMDATA] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
