CREATE TABLE [dbo].[PMPDMTRGR]
(
[OBJT] [int] NOT NULL,
[EVNT] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENE] [int] NULL,
[ORDR] [int] NULL,
[TTIM] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TXTV] [int] NULL,
[MNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMTRGR_PK] ON [dbo].[PMPDMTRGR] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
