CREATE TABLE [dbo].[PMOBJT]
(
[OBJT] [int] NOT NULL,
[POID] [int] NOT NULL,
[CLSS] [int] NOT NULL,
[BRNC] [int] NOT NULL,
[VRSN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PVOB] [int] NOT NULL,
[FRZN] [int] NULL,
[LVRS] [int] NULL,
[VCMT] [int] NULL,
[GOID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OCUS] [int] NOT NULL,
[OCDT] [datetime] NULL,
[OMUS] [int] NOT NULL,
[OMDT] [datetime] NULL,
[NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STRN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMMT] [int] NULL,
[DSCR] [int] NULL,
[ANNT] [int] NULL,
[HIST] [int] NULL,
[OEXA] [int] NULL,
[BCOL] [int] NULL,
[CUSR] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDAT] [datetime] NULL,
[MUSR] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDAT] [datetime] NULL,
[MTMD] [int] NULL,
[CTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMOBJT_BRNC] ON [dbo].[PMOBJT] ([BRNC], [LVRS]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMOBJT_CODE] ON [dbo].[PMOBJT] ([CODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMOBJT_GOID] ON [dbo].[PMOBJT] ([GOID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMOBJT_NAME] ON [dbo].[PMOBJT] ([NAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOBJT_PK] ON [dbo].[PMOBJT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMOBJT_POID] ON [dbo].[PMOBJT] ([POID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMOBJT_PVOB] ON [dbo].[PMOBJT] ([PVOB]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
