CREATE TABLE [dbo].[PMBPMFLOW]
(
[OBJT] [int] NOT NULL,
[CNDA] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDE] [int] NULL,
[FTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TSPT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UDEF] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMFLOW_PK] ON [dbo].[PMBPMFLOW] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
