CREATE TABLE [dbo].[PMBMAP]
(
[OBJT] [int] NOT NULL,
[CRTR] [int] NULL,
[QURY] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBMAP_PK] ON [dbo].[PMBMAP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
