CREATE TABLE [dbo].[PMXSMAITM]
(
[OBJT] [int] NOT NULL,
[CNNT] [int] NULL,
[LANG] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SRCE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[XSID] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMXSMAITM_PK] ON [dbo].[PMXSMAITM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
