CREATE TABLE [dbo].[PMMDPK]
(
[MTMD] [int] NOT NULL,
[MTPK] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMMDPK_PK] ON [dbo].[PMMDPK] ([MTMD], [MTPK]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
