CREATE TABLE [dbo].[PMUSER]
(
[RUSR] [int] NOT NULL,
[NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SYST] [int] NOT NULL,
[RGHT] [int] NULL,
[CMMT] [int] NULL,
[EMAD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISGR] [int] NOT NULL,
[PSWD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OCUS] [int] NULL,
[OCDT] [datetime] NULL,
[OMUS] [int] NULL,
[OMDT] [datetime] NULL,
[RNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STTS] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMUSER_CODE] ON [dbo].[PMUSER] ([CODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMUSER_PK] ON [dbo].[PMUSER] ([RUSR]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
