CREATE TABLE [dbo].[PMIMDL]
(
[OBJT] [int] NOT NULL,
[IMDL] [int] NULL,
[SOID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOLC] [int] NULL,
[STYP] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMIMDL_PK] ON [dbo].[PMIMDL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
