CREATE TABLE [dbo].[PMCLSS]
(
[CLSS] [int] NOT NULL,
[LIBR] [int] NOT NULL,
[CLID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRNT] [int] NULL,
[NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGS] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCLSS_AK] ON [dbo].[PMCLSS] ([CLID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCLSS_PK] ON [dbo].[PMCLSS] ([CLSS]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
