CREATE TABLE [dbo].[PMCDMENTT]
(
[OBJT] [int] NOT NULL,
[GENE] [int] NULL,
[NBRC] [float] NULL,
[FOPT] [int] NULL,
[NMSP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMCDMENTT_PK] ON [dbo].[PMCDMENTT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
