CREATE TABLE [dbo].[PMILMBPRC]
(
[OBJT] [int] NOT NULL,
[PTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMBPRC_PK] ON [dbo].[PMILMBPRC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
