CREATE TABLE [dbo].[PMPDMTRGI]
(
[OBJT] [int] NOT NULL,
[DECL] [int] NULL,
[TXTV] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMTRGI_PK] ON [dbo].[PMPDMTRGI] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
