CREATE TABLE [dbo].[PMLDMENTT]
(
[OBJT] [int] NOT NULL,
[FOPT] [int] NULL,
[GENE] [int] NULL,
[NBRC] [float] NULL,
[NMSP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMLDMENTT_PK] ON [dbo].[PMLDMENTT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
