CREATE TABLE [dbo].[PMTRFT]
(
[OBJT] [int] NOT NULL,
[HMAP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMTRFT_PK] ON [dbo].[PMTRFT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
