CREATE TABLE [dbo].[PMRULE]
(
[OBJT] [int] NOT NULL,
[CEXP] [int] NULL,
[FLAG] [int] NULL,
[RTYP] [int] NULL,
[SEXP] [int] NULL,
[OCLC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMRULE_PK] ON [dbo].[PMRULE] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
