CREATE TABLE [dbo].[PMRLTX]
(
[CLSS] [int] NOT NULL,
[DSID] [int] NOT NULL,
[NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FLGS] [int] NOT NULL,
[PRNT] [int] NOT NULL,
[NFND] [int] NOT NULL,
[SEQN] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMRLTX_PK] ON [dbo].[PMRLTX] ([CLSS], [DSID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
