CREATE TABLE [dbo].[PMPDMSYNM]
(
[OBJT] [int] NOT NULL,
[ALIA] [int] NULL,
[PUBL] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMSYNM_PK] ON [dbo].[PMPDMSYNM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
