CREATE TABLE [dbo].[PMILMPUBL]
(
[OBJT] [int] NOT NULL,
[PTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMPUBL_PK] ON [dbo].[PMILMPUBL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
