CREATE TABLE [dbo].[PMPDMPROC]
(
[OBJT] [int] NOT NULL,
[FOOT] [int] NULL,
[HEAD] [int] NULL,
[PCDT] [int] NULL,
[TXTV] [int] NULL,
[MNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPROC_PK] ON [dbo].[PMPDMPROC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
