CREATE TABLE [dbo].[PMOOMOBJT]
(
[OBJT] [int] NOT NULL,
[MLPL] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMOBJT_PK] ON [dbo].[PMOOMOBJT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
