CREATE TABLE [dbo].[PMPDMTRGT]
(
[OBJT] [int] NOT NULL,
[EVNT] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTIM] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TXTV] [int] NULL,
[TRTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VWTR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMTRGT_PK] ON [dbo].[PMPDMTRGT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
