CREATE TABLE [dbo].[PMILMSUBS]
(
[OBJT] [int] NOT NULL,
[CWHR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMSUBS_PK] ON [dbo].[PMILMSUBS] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
