CREATE TABLE [dbo].[PMOOMGNRL]
(
[OBJT] [int] NOT NULL,
[VISI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMGNRL_PK] ON [dbo].[PMOOMGNRL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
