CREATE TABLE [dbo].[PMPDMUSER]
(
[OBJT] [int] NOT NULL,
[GENE] [int] NULL,
[GRNT] [int] NULL,
[GRTW] [int] NULL,
[PASS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RVOK] [int] NULL,
[OPTS] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMUSER_PK] ON [dbo].[PMPDMUSER] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
