CREATE TABLE [dbo].[PMILMDCNT]
(
[OBJT] [int] NOT NULL,
[ACTP] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDCNT_PK] ON [dbo].[PMILMDCNT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
