CREATE TABLE [dbo].[PMPDMPKTY]
(
[OBJT] [int] NOT NULL,
[PUBL] [int] NULL,
[STYP] [int] NULL,
[TYST] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPKTY_PK] ON [dbo].[PMPDMPKTY] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
