CREATE TABLE [dbo].[PMBPMVARB]
(
[OBJT] [int] NOT NULL,
[CNST] [int] NULL,
[ETYP] [int] NULL,
[PTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VALE] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMVARB_PK] ON [dbo].[PMBPMVARB] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
