CREATE TABLE [dbo].[PMDBMS]
(
[OBJT] [int] NOT NULL,
[CGLB] [int] NULL,
[FMLY] [int] NULL,
[SFML] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMDBMS_PK] ON [dbo].[PMDBMS] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
