CREATE TABLE [dbo].[PMOOMACTV]
(
[OBJT] [int] NOT NULL,
[ACTN] [int] NULL,
[ACTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM] [int] NULL,
[DRTN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOPT] [int] NULL,
[NMSP] [int] NULL,
[TMOT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMACTV_PK] ON [dbo].[PMOOMACTV] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
