CREATE TABLE [dbo].[PMILMEVSC]
(
[OBJT] [int] NOT NULL,
[EVNT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCPT] [int] NULL,
[VERS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMEVSC_PK] ON [dbo].[PMILMEVSC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
