CREATE TABLE [dbo].[PMPRJFDOC]
(
[OBJT] [int] NOT NULL,
[BRNI] [int] NULL,
[DOCI] [int] NULL,
[DOCV] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXDT] [datetime] NULL,
[FEXT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REPI] [int] NULL,
[URLC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPRJFDOC_PK] ON [dbo].[PMPRJFDOC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
