CREATE TABLE [dbo].[PMPDMPROF]
(
[OBJT] [int] NOT NULL,
[CHAL] [int] NULL,
[CHCS] [int] NULL,
[CHFM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHFU] [int] NULL,
[CHIV] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHLN] [int] NULL,
[CHNA] [int] NULL,
[CHRF] [int] NULL,
[CHRL] [int] NULL,
[CHVL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHXL] [int] NULL,
[CLSS] [int] NULL,
[COLN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFDY] [int] NULL,
[DFHR] [int] NULL,
[DFMI] [int] NULL,
[DFMO] [int] NULL,
[DFSC] [int] NULL,
[DFYR] [int] NULL,
[DLDY] [int] NULL,
[DLHR] [int] NULL,
[DLMI] [int] NULL,
[DLMO] [int] NULL,
[DLSC] [int] NULL,
[DLYR] [int] NULL,
[DSDY] [int] NULL,
[DSHR] [int] NULL,
[DSMI] [int] NULL,
[DSMO] [int] NULL,
[DSSC] [int] NULL,
[DSYR] [int] NULL,
[HQRY] [int] NULL,
[NBDC] [int] NULL,
[NBDG] [int] NULL,
[NBHV] [float] NULL,
[NBLV] [float] NULL,
[NBST] [float] NULL,
[ODSL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ODSN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ODSP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OFIL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEQU] [int] NULL,
[TABL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VALS] [int] NULL,
[VSRC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPROF_PK] ON [dbo].[PMPDMPROF] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
