CREATE TABLE [dbo].[PMRQMUSRA]
(
[OBJT] [int] NOT NULL,
[ATYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMRQMUSRA_PK] ON [dbo].[PMRQMUSRA] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
