CREATE TABLE [dbo].[PMPRJMDOC]
(
[OBJT] [int] NOT NULL,
[BRNI] [int] NULL,
[DOCI] [int] NULL,
[DOCV] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ECLS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXDT] [datetime] NULL,
[FEXT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REPI] [int] NULL,
[URLC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPRJMDOC_PK] ON [dbo].[PMPRJMDOC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
