CREATE TABLE [dbo].[PMRQMTLNK]
(
[OBJT] [int] NOT NULL,
[BKMK] [int] NULL,
[LKTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMRQMTLNK_PK] ON [dbo].[PMRQMTLNK] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
