CREATE TABLE [dbo].[PMXFIL]
(
[OBJT] [int] NOT NULL,
[CNTI] [int] NULL,
[XNAM] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMXFIL_PK] ON [dbo].[PMXFIL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
