CREATE TABLE [dbo].[part_standard]
(
[part] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[price] [numeric] (20, 6) NULL,
[cost] [numeric] (20, 6) NULL,
[account_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[material] [numeric] (20, 6) NULL,
[labor] [numeric] (20, 6) NULL,
[burden] [numeric] (20, 6) NULL,
[other] [numeric] (20, 6) NULL,
[cost_cum] [numeric] (20, 6) NULL,
[material_cum] [numeric] (20, 6) NULL,
[burden_cum] [numeric] (20, 6) NULL,
[other_cum] [numeric] (20, 6) NULL,
[labor_cum] [numeric] (20, 6) NULL,
[flag] [int] NULL,
[premium] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtd_cost] [numeric] (20, 6) NULL,
[qtd_material] [numeric] (20, 6) NULL,
[qtd_labor] [numeric] (20, 6) NULL,
[qtd_burden] [numeric] (20, 6) NULL,
[qtd_other] [numeric] (20, 6) NULL,
[qtd_cost_cum] [numeric] (20, 6) NULL,
[qtd_material_cum] [numeric] (20, 6) NULL,
[qtd_labor_cum] [numeric] (20, 6) NULL,
[qtd_burden_cum] [numeric] (20, 6) NULL,
[qtd_other_cum] [numeric] (20, 6) NULL,
[planned_cost] [numeric] (20, 6) NULL,
[planned_material] [numeric] (20, 6) NULL,
[planned_labor] [numeric] (20, 6) NULL,
[planned_burden] [numeric] (20, 6) NULL,
[planned_other] [numeric] (20, 6) NULL,
[planned_cost_cum] [numeric] (20, 6) NULL,
[planned_material_cum] [numeric] (20, 6) NULL,
[planned_labor_cum] [numeric] (20, 6) NULL,
[planned_burden_cum] [numeric] (20, 6) NULL,
[planned_other_cum] [numeric] (20, 6) NULL,
[frozen_cost] [numeric] (20, 6) NULL,
[frozen_material] [numeric] (20, 6) NULL,
[frozen_burden] [numeric] (20, 6) NULL,
[frozen_labor] [numeric] (20, 6) NULL,
[frozen_other] [numeric] (20, 6) NULL,
[frozen_cost_cum] [numeric] (20, 6) NULL,
[frozen_material_cum] [numeric] (20, 6) NULL,
[frozen_burden_cum] [numeric] (20, 6) NULL,
[frozen_labor_cum] [numeric] (20, 6) NULL,
[frozen_other_cum] [numeric] (20, 6) NULL,
[cost_changed_date] [datetime] NULL,
[qtd_changed_date] [datetime] NULL,
[planned_changed_date] [datetime] NULL,
[frozen_changed_date] [datetime] NULL,
[os_cost] [numeric] (20, 6) NULL,
[os_cost_cum] [numeric] (20, 6) NULL,
[os_qtd_cost] [numeric] (20, 6) NULL,
[os_qtd_cost_cum] [numeric] (20, 6) NULL,
[os_planned_cost] [numeric] (20, 6) NULL,
[os_planned_cost_cum] [numeric] (20, 6) NULL,
[os_frozen_cost] [numeric] (20, 6) NULL,
[os_frozen_cost_cum] [numeric] (20, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[part_standard] ADD CONSTRAINT [part_standard_x] PRIMARY KEY CLUSTERED  ([part]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[part_standard] ADD CONSTRAINT [FK__part_stand__part__0FB750B3] FOREIGN KEY ([part]) REFERENCES [dbo].[part] ([part])
GO
