CREATE TABLE [dbo].[PMXSMCMAP]
(
[OBJT] [int] NOT NULL,
[CRTR] [int] NULL,
[DELT] [int] NULL,
[EXPR] [int] NULL,
[INSR] [int] NULL,
[REVB] [int] NULL,
[SLCT] [int] NULL,
[UPDT] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMXSMCMAP_PK] ON [dbo].[PMXSMCMAP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
