CREATE TABLE [dbo].[PMPDMPKEX]
(
[OBJT] [int] NOT NULL,
[PRAG] [int] NULL,
[PUBL] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPKEX_PK] ON [dbo].[PMPDMPKEX] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
