CREATE TABLE [dbo].[PMOPTS]
(
[NAME] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOPTS_PK] ON [dbo].[PMOPTS] ([NAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
