CREATE TABLE [dbo].[PMOOMPARM]
(
[OBJT] [int] NOT NULL,
[ARAY] [int] NULL,
[ARSZ] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTTP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WDTP] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMPARM_PK] ON [dbo].[PMOOMPARM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
