CREATE TABLE [dbo].[PMPRJLSTD]
(
[OBJT] [int] NOT NULL,
[LOST] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OKND] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPRJLSTD_PK] ON [dbo].[PMPRJLSTD] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
