CREATE TABLE [dbo].[PMSRPL]
(
[OBJT] [int] NOT NULL,
[RATT] [int] NULL,
[RCLS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCOL] [int] NULL,
[ROID] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RUOL] [int] NULL,
[RNAT] [int] NULL,
[RNCO] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMSRPL_PK] ON [dbo].[PMSRPL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
