CREATE TABLE [dbo].[PMRLSH]
(
[RTYP] [int] NOT NULL,
[SRCE] [int] NOT NULL,
[TRGT] [int] NOT NULL,
[PRNT] [int] NOT NULL,
[NUMR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMRLSH_PK] ON [dbo].[PMRLSH] ([RTYP], [SRCE], [TRGT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMRLSH_SRCE] ON [dbo].[PMRLSH] ([SRCE], [PRNT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMRLSH_TRGT] ON [dbo].[PMRLSH] ([TRGT], [SRCE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
