CREATE TABLE [dbo].[PMPDMPARM]
(
[OBJT] [int] NOT NULL,
[DTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DVAL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MLEN] [int] NULL,
[PREC] [int] NULL,
[PTTP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMPARM_PK] ON [dbo].[PMPDMPARM] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
