CREATE TABLE [dbo].[PMPDMWSOP]
(
[OBJT] [int] NOT NULL,
[CNUS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMPL] [int] NULL,
[OTYP] [int] NULL,
[RAUT] [int] NULL,
[SCNC] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMPDMWSOP_PK] ON [dbo].[PMPDMWSOP] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
