CREATE TABLE [dbo].[PMBPMSYNC]
(
[OBJT] [int] NOT NULL,
[ACTN] [int] NULL,
[TMOT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMSYNC_PK] ON [dbo].[PMBPMSYNC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
