CREATE TABLE [dbo].[PMILMRPRC]
(
[OBJT] [int] NOT NULL,
[DTSC] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOGN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSWD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMRPRC_PK] ON [dbo].[PMILMRPRC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
