CREATE TABLE [dbo].[PMILMFFIL]
(
[OBJT] [int] NOT NULL,
[FMOD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FPAT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSEP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HEAD] [int] NULL,
[PTYP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RAWD] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMFFIL_PK] ON [dbo].[PMILMFFIL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
