CREATE TABLE [dbo].[PMOOMCMPI]
(
[OBJT] [int] NOT NULL,
[ACCP] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISP] [int] NULL,
[MULT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCMT] [int] NULL,
[WIIF] [int] NULL,
[WTXT] [int] NULL,
[WURL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WXTN] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMCMPI_PK] ON [dbo].[PMOOMCMPI] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
