CREATE TABLE [dbo].[PMILMDBIN]
(
[OBJT] [int] NOT NULL,
[SQRY] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMDBIN_PK] ON [dbo].[PMILMDBIN] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
