CREATE TABLE [dbo].[PMBPMDTRS]
(
[OBJT] [int] NOT NULL,
[EXPR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMBPMDTRS_PK] ON [dbo].[PMBPMDTRS] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
