CREATE TABLE [dbo].[PMPDMTKEY]
(
[OBJT] [int] NOT NULL,
[CNST] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPTS] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMTKEY_PK] ON [dbo].[PMPDMTKEY] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
