CREATE TABLE [dbo].[PMXSMENTT]
(
[OBJT] [int] NOT NULL,
[NOTN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRMT] [int] NULL,
[PUBL] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYST] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VALE] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMXSMENTT_PK] ON [dbo].[PMXSMENTT] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
