CREATE TABLE [dbo].[PMTEMP]
(
[SESS] [int] NOT NULL,
[INT1] [int] NULL,
[INT2] [int] NULL,
[STR1] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR2] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUM1] [int] NULL,
[NUM2] [int] NULL,
[NUM3] [int] NULL,
[NUM4] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMTEMP_SESS] ON [dbo].[PMTEMP] ([SESS], [NUM1]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMTEMP_NUM2] ON [dbo].[PMTEMP] ([SESS], [NUM2]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PMTEMP_NUM3] ON [dbo].[PMTEMP] ([SESS], [NUM3]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
