CREATE TABLE [dbo].[PMOOMDTSC]
(
[OBJT] [int] NOT NULL,
[CNCT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTSR] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LGIN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ODBC] [int] NULL,
[PSWD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMOOMDTSC_PK] ON [dbo].[PMOOMDTSC] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
