CREATE TABLE [dbo].[PMLDMINHR]
(
[OBJT] [int] NOT NULL,
[COMP] [int] NULL,
[EXCL] [int] NULL,
[INHA] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMLDMINHR_PK] ON [dbo].[PMLDMINHR] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
