CREATE TABLE [dbo].[PMPDMJIDX]
(
[OBJT] [int] NOT NULL,
[FOOT] [int] NULL,
[HEAD] [int] NULL,
[OPTS] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPDMJIDX_PK] ON [dbo].[PMPDMJIDX] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
