CREATE TABLE [dbo].[PMILMSCOL]
(
[OBJT] [int] NOT NULL,
[ORDR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [PMILMSCOL_PK] ON [dbo].[PMILMSCOL] ([OBJT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
