SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[cdivw_blanket_po] (
	po_header_ship_to_destination,   
	po_header_plant,   
	po_header_type,   
	po_header_release_no,   
	vendor_company,   
	vendor_address_1,   
	vendor_address_2,   
	vendor_address_3,   
	vendor_fax,   
	po_header_fob,   
	parameters_company_name,   
	parameters_address_1,   
	parameters_address_2,   
	parameters_address_3,   
	parameters_phone_number,   
	vendor_buyer,   
	vendor_name,   
	part_cross_ref,   
	po_header_po_date,   
	po_header_freight_type,   
	po_header_po_number,   
	po_header_vendor_code,
	po_header_buyer,   
	carrier_name,   
	po_header_terms,   
	po_header_notes,   
	part_vendor_receiving_um,   
	part_vendor_vendor,   
	part_vendor_vendor_part,   
	po_header_blanket_part,   
	part_name,   
	vendor_address_4,   
	vendor_address_5,   
	vendor_address_6,   
	destination_name,   
	destination_address_1,   
	destination_address_2,   
	destination_address_3,   
	destination_address_4,   
	destination_address_5,   
	destination_address_6,   
	vendor_contact,
	part_vendor_note,
	part_vendor_part) as
select	po_header.ship_to_destination,   
	po_header.plant,   
	po_header.type,   
	po_header.release_no,   
	vendor.company,   
	vendor.address_1,   
	vendor.address_2,   
	vendor.address_3,   
	vendor.fax,   
	po_header.fob,   
	parameters.company_name,   
	parameters.address_1,   
	parameters.address_2,   
	parameters.address_3,   
	parameters.phone_number,   
	vendor.buyer,   
	vendor.name,   
	part.cross_ref,   
	po_header.po_date,   
	po_header.freight_type,   
	po_header.po_number,   
	po_header.vendor_code,
	po_header.buyer,   
	carrier.name,   
	po_header.terms,   
	po_header.notes,   
	part_vendor.receiving_um,   
	part_vendor.vendor,   
	part_vendor.vendor_part,   
	po_header.blanket_part,   
	part.name,   
	vendor.address_4,   
	vendor.address_5,   
	vendor.address_6,   
	destination.name,   
	destination.address_1,   
	destination.address_2,   
	destination.address_3,   
	destination.address_4,   
	destination.address_5,   
	destination.address_6,   
	vendor.contact,
	part_vendor.note,
	part_vendor.part
from	po_header  
	left outer join destination ON po_header.ship_to_destination = destination.destination,   
	part,   
	vendor,   
	part_vendor,   
	parameters,   
	carrier
where	( po_header.vendor_code = vendor.code ) and  
	( po_header.vendor_code = part_vendor.vendor ) and  
	( po_header.ship_via = carrier.scac ) and 
	( part_vendor.part = part.part ) and  
	( part_vendor.part in (select part_number from po_detail where po_detail.po_number = po_header.po_number and isnull(selected_for_print,'N') = 'Y' ) )
GO
