SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[cdivw_po_inquiry] (
 	po_number,   
	vendor_code,   
	po_date,   
	date_due,   
	terms,   
	fob,   
	ship_via,   
	ship_to_destination,   
	status,   
	type,   
	description,   
	plant,   
	freight_type,   
	buyer,   
	printed,   
	total_amount,   
	shipping_fee,   
	sales_tax,   
	blanket_orderded_qty,   
	blanket_frequency,   
	blanket_duration,   
	blanket_qty_per_release,   
	blanket_part,   
	blanket_vendor_part,   
	price,   
	std_unit,   
	ship_type,   
	flag,   
	release_no,   
	release_control,   
	tax_rate,   
	scheduled_time) as  
select	distinct po_header.po_number,   
	po_header.vendor_code,   
	po_header.po_date,   
	po_header.date_due,   
	po_header.terms,   
	po_header.fob,   
	po_header.ship_via,   
	po_header.ship_to_destination,   
	po_header.status,   
	po_header.type,   
	po_header.description,   
	po_header.plant,   
	po_header.freight_type,   
	po_header.buyer,   
	po_header.printed,   
	po_header.total_amount,   
	po_header.shipping_fee,   
	po_header.sales_tax,   
	po_header.blanket_orderded_qty,   
	po_header.blanket_frequency,   
	po_header.blanket_duration,   
	po_header.blanket_qty_per_release,   
	isnull(po_header.blanket_part, po_detail.part_number) as blanket_part,   
	po_header.blanket_vendor_part,   
	po_header.price,   
	po_header.std_unit,   
	po_header.ship_type,   
	po_header.flag,   
	po_header.release_no,   
	po_header.release_control,   
	po_header.tax_rate,   
	po_header.scheduled_time  
from	po_header
	left outer join po_detail on po_detail.po_number = po_header.po_number
GO
