SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create view [FT].[REFERENTIAL_CONSTRAINTS_COLUMN_USAGE]
as
select
	KCU1.CONSTRAINT_CATALOG as 'CONSTRAINT_CATALOG'
,	KCU1.CONSTRAINT_SCHEMA as 'CONSTRAINT_SCHEMA'
,	KCU1.CONSTRAINT_NAME as 'CONSTRAINT_NAME'
,	KCU1.TABLE_CATALOG as 'TABLE_CATALOG'
,	KCU1.TABLE_SCHEMA as 'TABLE_SCHEMA'
,	KCU1.TABLE_NAME as 'TABLE_NAME'
,	KCU1.COLUMN_NAME as 'COLUMN_NAME'
,	KCU1.ORDINAL_POSITION as 'ORDINAL_POSITION'
,	KCU2.CONSTRAINT_CATALOG as 'UNIQUE_CONSTRAINT_CATALOG'
,	KCU2.CONSTRAINT_SCHEMA as 'UNIQUE_CONSTRAINT_SCHEMA'
,	KCU2.CONSTRAINT_NAME as 'UNIQUE_CONSTRAINT_NAME'
,	KCU2.TABLE_CATALOG as 'UNIQUE_TABLE_CATALOG'
,	KCU2.TABLE_SCHEMA as 'UNIQUE_TABLE_SCHEMA'
,	KCU2.TABLE_NAME as 'UNIQUE_TABLE_NAME'
,	KCU2.COLUMN_NAME as 'UNIQUE_COLUMN_NAME'
from
	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
	join INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU1
		on KCU1.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG
		   and KCU1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
		   and KCU1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME
	join INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU2
		on KCU2.CONSTRAINT_CATALOG = RC.UNIQUE_CONSTRAINT_CATALOG
		   and KCU2.CONSTRAINT_SCHEMA = RC.UNIQUE_CONSTRAINT_SCHEMA
		   and KCU2.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME
where
	KCU1.ORDINAL_POSITION = KCU2.ORDINAL_POSITION;

GO
