USE [master]
go

/****** Object:  Database [FxEDI]    Script Date: 6/7/2019 5:48:00 PM ******/
CREATE DATABASE [FxEDI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FxEDI', FILENAME = N'E:\MonitorDb\FxEDI_Data.MDF' , SIZE = 3014336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%),
 FILEGROUP [RAWDATA] CONTAINS FILESTREAM  DEFAULT 
( NAME = N'FxEDI_raw', FILENAME = N'E:\MonitorDb\FxEDI_raw' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'FxEDI_Log', FILENAME = N'E:\MonitorDb\FxEDI_log.LDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FxEDI].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [FxEDI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FxEDI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FxEDI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FxEDI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FxEDI] SET ARITHABORT OFF 
GO

ALTER DATABASE [FxEDI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FxEDI] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [FxEDI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FxEDI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FxEDI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FxEDI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FxEDI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FxEDI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FxEDI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FxEDI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FxEDI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FxEDI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FxEDI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FxEDI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FxEDI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FxEDI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FxEDI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FxEDI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FxEDI] SET  MULTI_USER 
GO

ALTER DATABASE [FxEDI] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [FxEDI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FxEDI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FxEDI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FxEDI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FxEDI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FxEDI] SET  READ_WRITE 
GO


